{{- if .Values.backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: backup-secret
type: Opaque
stringData:
  BACKUP_ACCESS_KEY: {{ .Values.secrets.backupAccessKey | quote }}
  BACKUP_SECRET_KEY: {{ .Values.secrets.backupSecretKey | quote }}
  BACKUP_BUCKET: {{ .Values.secrets.backupBucket | quote }}
  BACKUP_ENDPOINT: {{ .Values.secrets.backupEndpoint | quote }}
  BACKUP_REGION: {{ .Values.secrets.backupRegion | quote }}
{{- end }}
