apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ if .Values.tenants.enabled }}PathPrefix(`/`){{ else }}Host(`{{ .Values.domain }}`){{ end }}
      kind: Rule
      services:
        - name: django
          port: 8000
  tls:
    secretName: cloudflare-origin-cert
