# Generated by Django 6.1 on 2026-08-16 10:42

from django.db import migrations, models

import vrillees_website.company.utils


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="picture",
            field=models.ImageField(
                upload_to=vrillees_website.company.utils.upload_handler
            ),
        ),
    ]
