name: vrillees_website:checks
on: workflow_call
jobs:
  precommit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
        with:
          persist-credentials: false
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd  # v3
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5
        with:
          python-version: "3.14.0"
          cache: "pip"
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1
  unittests:
    needs: precommit
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      postgres:
        image: postgres:18.1-bookworm
        env:
          POSTGRES_PASSWORD: password # pragma: allowlist secret
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39  # v3
        with:
          version: "0.9.8"
          enable-cache: true
          cache-dependency-glob: |
            **/uv.lock
            **/pyproject.toml
      - run: uv python install 3.14.0
      - run: uv sync --frozen --all-extras --no-install-project
      - run: uv run basedpyright
      - run: uv run pytest
  e2etests:
    needs: precommit
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      postgres:
        image: postgres:18.1-bookworm
        env:
          POSTGRES_PASSWORD: password # pragma: allowlist secret
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39  # v3
        with:
          version: "0.9.8"
          enable-cache: true
          cache-dependency-glob: |
            **/uv.lock
            **/pyproject.toml
      - run: uv python install 3.14.0
      - run: uv sync --frozen --all-extras --no-install-project
      - run: uv run playwright install --with-deps chromium
      - run: uv run python manage.py tailwind build
      - run: uv run pytest -c playwright.ini
